### ISSUE TITLE
Redundancy features

### ISSUE THREAD

**Issue by token2** [token2/TOTPRadius#18]
1) Any appliance can be configured in master of slave mode
2) Appliances in slave mode: 
                  2.1 - will only contain a read-only database
                  2.2  - will periodically synchronize with the their master appliance via HTTPS REST (Hostname and API name to be configured on both nodes) - 1 minute minimum (cron's limitation)
                  2.3 - will have the same web interface, but user management (adding/editing/deleting) will be disabled
                  2.4 - will have no self-enrollment features
                  2.5 - will require no additional user licenses (user licenses are only needed for adding users, which is disabled as per 2.3 and 2.4)
3) Any appliance in slave mode can be switched back to master mode, so the master/slave feature can be considered a cold spare (manual re-licensing will need to be requested)

**Comment by token2** [comment]
-- DB replication via CSV transfer
    -- set cron via gui gives error localhost cron[558]: (*system*) INSECURE MODE (group/other writa
    -- admin account replication??

**Comment by token2** [comment]
-- SSL checks & Root CA for remote master node

**Comment by token2** [comment]
-- Change wizard wording
-- SSL Check change permission denied message

**Comment by token2** [comment]
-- More visible Slave mode message

**Comment by eminhuseynov** [comment]
- Connection timed out or resolved issues error screen on manual replicate

**Comment by eminhuseynov** [comment]
- Hyperv deployment - version mismatch (5.0 vs 8.0 - Win10 not compatible with Win2012)

**Comment by eminhuseynov** [comment]
Edit user button after creation
